version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: clubdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
